"""BO helpers for the unified Bézier-superset parameterisation (Step 4/5).

Unlike the RadialSpline repair decoder (every box point feasible), the Bézier
superset uses the cheap geometry validator as a HARD CONSTRAINT (no feasibility
GP, per CLAUDE.md). Uniform points in [0, r_max]^D are ~never feasible, so:

- the BO box is scaled to the warm-start region (`warmstart_box`), and
- the acquisition is optimised over a FEASIBLE candidate pool generated by
  perturbing feasible anchors (`sample_feasible` / `optimize_acqf_feasible`),
  not by gradient ascent over the raw box.

All functions operate in UNIT coordinates u in [0,1]^D; `decode(u)` maps
u -> raw params (lo + u*span) -> barriers and runs the validator.
"""

from __future__ import annotations

import numpy as np
import torch


def warmstart_box(Xpool, gen, margin_frac=0.15):
    """Per-dimension box covering the warm-start designs with a relative margin,
    clipped to the generator's hard bounds. Returns (lo, span) float arrays."""
    Xpool = np.asarray(Xpool, float)
    lo_d, hi_d = Xpool.min(0), Xpool.max(0)
    width = np.maximum(hi_d - lo_d, 1e-6)
    lo = lo_d - margin_frac * width
    hi = hi_d + margin_frac * width
    glo, ghi = gen.bounds
    lo = np.maximum(lo, glo)
    hi = np.minimum(hi, ghi)
    span = np.maximum(hi - lo, 1e-9)
    return lo.astype(float), span.astype(float)


def decode_feasible(gen, u, lo, span):
    """u (D,) unit -> True if the decoded barrier set passes the validator."""
    u = np.clip(np.asarray(u, float), 0.0, 1.0)
    try:
        gen.set_parameters(lo + u * span)
        return bool(gen.feasible_barriers(gen.generate_barriers()))
    except Exception:
        return False


def to_unit(X, lo, span):
    return np.clip((np.asarray(X, float) - lo) / span, 0.0, 1.0)


def sample_feasible(gen, n, lo, span, anchors, rng, sigma=0.05, max_tries=200):
    """n feasible unit points by perturbing random feasible `anchors` (unit) with
    Gaussian noise (std `sigma` in unit space) and rejection-filtering. `sigma`
    may be a scalar or a 1-D array drawn per sample. Raises if it can't fill n."""
    anchors = np.atleast_2d(np.asarray(anchors, float))
    out = []
    tries = 0
    while len(out) < n and tries < max_tries:
        tries += 1
        k = min(4 * (n - len(out)), 256)
        a = anchors[rng.integers(0, len(anchors), size=k)]
        s = sigma if np.isscalar(sigma) else rng.choice(sigma, size=k)
        cand = np.clip(a + rng.normal(0, 1, (k, anchors.shape[1])) * np.reshape(s, (-1, 1)), 0, 1)
        for u in cand:
            if decode_feasible(gen, u, lo, span):
                out.append(u)
                if len(out) >= n:
                    break
    if len(out) < n:
        raise RuntimeError(f"sample_feasible: only {len(out)}/{n} feasible after {max_tries} tries "
                           f"(sigma={sigma}); region may be too thin — lower sigma or add anchors")
    return np.array(out[:n])


def optimize_acqf_feasible(acqf, gen, lo, span, anchors, rng,
                           n_cand=2048, sigmas=(0.02, 0.05, 0.1, 0.2), q=1):
    """Feasibility-constrained acqf optimisation (no second GP): build a feasible
    candidate pool by perturbing `anchors` at a range of step sizes, evaluate the
    acquisition on it, and return the top-q unit candidates + their acqf values.

    anchors: (m,D) unit points known feasible (e.g. all evaluated feasible designs).
    Returns (cand (q,D) np.float64, vals (q,) np.float64).
    """
    anchors = np.atleast_2d(np.asarray(anchors, float))
    per = max(1, n_cand // len(sigmas))
    pool = [anchors]  # always include the anchors themselves
    for s in sigmas:
        try:
            pool.append(sample_feasible(gen, per, lo, span, anchors, rng, sigma=s))
        except RuntimeError:
            pass  # this step size too large for the feasible region; skip
    U = np.unique(np.vstack(pool), axis=0)
    with torch.no_grad():
        Ut = torch.as_tensor(U, dtype=torch.get_default_dtype()).unsqueeze(1)  # (b,1,D)
        vals = acqf(Ut).cpu().numpy().ravel()
    top = np.argsort(vals)[::-1][:q]
    return U[top], vals[top]
